version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: david123
      MYSQL_DATABASE: dog_grooming_db
      MYSQL_USER: david
      MYSQL_PASSWORD: david123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: